import React from "react";
import styles from "./Problem.module.css";

type Problem = {
  /**
   * 横幅
   */
  width: number;
  /**
   * 高さ
   */
  height: number;
  /**
   * セル。-1は空白、0～3なら数値の入ったセル
   */
  cells: number[][];
}

const ProblemRow = ({cellsRow}: {cellsRow: number[]}) => {
  return (
    <tr>
      {cellsRow.map((cell, index) => (
        <td key={index} className={styles.cell}>
          {cell === -1 ? "" : cell}
        </td>
      ))}
    </tr>
  );
}

const ProblemFrame = ({problem}: {problem: Problem}) => {
  return (
    <table className={styles.frame}>
      <tbody>
        {problem.cells.map((cellsRow, index) => (
          <ProblemRow key={index} cellsRow={cellsRow} />
        ))}
      </tbody>
    </table>
  );
};

const p: Problem = {
  width: 3,
  height: 3,
  cells: [
    [1, 2, 1],
    [-1, 0, -1],
    [2, 1, 1],
  ],
}
const pro = {
  problem: p
}

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <ProblemFrame problem={p}></ProblemFrame>
  );
}

